"""Detector: False Rate Limiter — synthetic entries (Bug B3, #40584)."""

from __future__ import annotations

from llm_relay.detect.base import BaseDetector
from llm_relay.detect.models import Finding, FeatureFlagsConfig, ParsedSession, Severity


class SyntheticDetector(BaseDetector):
    detector_id = "synthetic"
    display_name = "False Rate Limiter (B3)"

    def check(self, session: ParsedSession, featureflags: FeatureFlagsConfig | None = None) -> list[Finding]:
        evidence: list[str] = []

        for entry in session.entries:
            if entry.type != "assistant":
                continue
            if not entry.is_synthetic:
                continue

            ts = entry.timestamp or "unknown time"
            uid = entry.uuid[:12] if entry.uuid else "?"
            evidence.append(f"Entry {uid} at {ts}")

        if not evidence:
            return []

        count = len(evidence)
        return [
            Finding(
                detector_id=self.detector_id,
                severity=Severity.CRITICAL,
                title=self.display_name,
                detail=(
                    f"{count} synthetic entr{'y' if count == 1 else 'ies'} with model=<synthetic> "
                    f"and zero tokens — client blocked API calls with fake rate limit errors."
                ),
                recommendation=(
                    "These are false alarms generated by the client, not real API rate limits. "
                    "If you saw 'Rate limit reached' messages, they may not have been real."
                ),
                evidence=evidence[:10],
                bug_ref="https://github.com/anthropics/claude-code/issues/40584",
            )
        ]
